CREATE TABLE FILES (
  F_ID NUMBER(10) PRIMARY KEY,
  F_NAME VARCHAR2(255) NOT NULL,
  F_TYPE RAW(2000),
  F_SIZE NUMBER(10),
  F_DATECREATE DATE,
  F_DATECHANGE DATE,
  F_DESCRIBE VARCHAR2(4000),
  F_PATH BLOB,
  F_ISDELETED NUMBER(1) DEFAULT 0
);

-- T?o b?ng FOLDERS
CREATE TABLE FOLDERS (
  FD_ID NUMBER(10) PRIMARY KEY,
  FD_NAME VARCHAR2(255) NOT NULL,
  FD_FATHER NUMBER(10) REFERENCES FOLDERS(FD_ID),
  FD_DESCRIBE VARCHAR2(4000)
);

-- T?o b?ng RECYCLEBIN
CREATE TABLE RECYCLEBIN (
  R_ID NUMBER(10) PRIMARY KEY,
  F_ID NUMBER(10),
  R_DELETEDDATE DATE
);

-- T?o b?ng FILEPERMISSIONS
CREATE TABLE FILEPERMISSIONS (
  FP_ID NUMBER(10) PRIMARY KEY,
  F_ID NUMBER(10) NOT NULL,
  FD_ID NUMBER(10) NOT NULL,
  R_ID NUMBER(10) NOT NULL,
  FP_ACCESS VARCHAR2(10)
);

ALTER TABLE FILEPERMISSIONS
ADD CONSTRAINT fk_file_id FOREIGN KEY (F_ID) REFERENCES FILES (F_ID)

ALTER TABLE FILEPERMISSIONS
ADD CONSTRAINT fk_recyclebin_id FOREIGN KEY (R_ID) REFERENCES RECYCLEBIN (R_ID)

ALTER TABLE FILEPERMISSIONS
ADD CONSTRAINT fk_folder_id FOREIGN KEY (FD_ID) REFERENCES FOLDERS (FD_ID)

ALTER TABLE RECYCLEBIN
ADD CONSTRAINT fk_file_recyclebin_id FOREIGN KEY (F_ID) REFERENCES FILES (F_ID)