
package qlfile.FORM;

import Class.AuditUpdateUser;
import Class.File;
import Class.JDBCConnection;
import Class.SYSConnection;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;

public class AuditUseTrigger extends javax.swing.JFrame {
    private String userNameIO, passWordIO;

    private AuditUseTrigger() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void setUserNameIO(String userNameIO) {
        this.userNameIO = userNameIO;
    }

    public void setPassWordIO(String passWordIO) {
        this.passWordIO = passWordIO;
    }
    
    private JDBCConnection databaseConnection = new JDBCConnection();
    private SYSConnection sysConnection=new SYSConnection();
    public Connection connection;
    private Connection connection2 = sysConnection.getConnection();
    DefaultTableModel model;
    List<AuditUpdateUser> list;
    
    public AuditUseTrigger(String userNameIO, String passWordIO){
        initComponents();
        this.userNameIO = userNameIO;
        this.passWordIO = passWordIO;
        connection = databaseConnection.getConnection(userNameIO, passWordIO);
        model  = (DefaultTableModel) tbl_info.getModel();
        list = new ArrayList<>();
        this.setLocationRelativeTo(null);
        setUsername();
        setTime();
        
    }
    
    public void setUsername() {
        lblHienthi.setText(userNameIO);
    }
    public void setTime(){
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new swing.PanelRound();
        title = new swing.PanelRound();
        title2 = new swing.PanelRound();
        lblHienthi1 = new javax.swing.JLabel();
        lblHienthi = new javax.swing.JLabel();
        title1 = new swing.PanelRound();
        txt_search = new textfield.TextField();
        btn_search = new javax.swing.JLabel();
        btn_search4 = new javax.swing.JLabel();
        title3 = new swing.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_info = new javax.swing.JTable();
        btn_load = new swing.ButtonGradient();
        lblHienthi6 = new javax.swing.JLabel();
        btn_quaLaiMain = new swing.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound2.setColorEnd(new java.awt.Color(0, 0, 0));
        panelRound2.setColorStart(new java.awt.Color(51, 51, 51));
        panelRound2.setPreferredSize(new java.awt.Dimension(1200, 690));

        title.setColorEnd(new java.awt.Color(102, 102, 102));
        title.setColorStart(new java.awt.Color(102, 102, 102));
        title.setRoundBottomLeft(15);
        title.setRoundBottomRight(15);
        title.setRoundTopLeft(15);
        title.setRoundTopRight(15);

        title2.setColorEnd(new java.awt.Color(0, 0, 0));
        title2.setColorStart(new java.awt.Color(51, 51, 51));
        title2.setRoundBottomLeft(15);
        title2.setRoundBottomRight(15);
        title2.setRoundTopLeft(15);
        title2.setRoundTopRight(15);

        lblHienthi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi1.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUser.png"))); // NOI18N
        lblHienthi1.setFocusable(false);
        lblHienthi1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi1.setIconTextGap(10);

        lblHienthi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi.setText("User name");
        lblHienthi.setFocusable(false);
        lblHienthi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi.setIconTextGap(10);

        javax.swing.GroupLayout title2Layout = new javax.swing.GroupLayout(title2);
        title2.setLayout(title2Layout);
        title2Layout.setHorizontalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHienthi1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHienthi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        title2Layout.setVerticalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblHienthi1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHienthi)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title1.setColorEnd(new java.awt.Color(102, 102, 102));
        title1.setColorStart(new java.awt.Color(102, 102, 102));
        title1.setPreferredSize(new java.awt.Dimension(900, 50));
        title1.setRoundBottomLeft(15);
        title1.setRoundBottomRight(15);
        title1.setRoundTopLeft(15);
        title1.setRoundTopRight(15);

        txt_search.setForeground(new java.awt.Color(0, 204, 204));
        txt_search.setCaretColor(new java.awt.Color(0, 153, 153));
        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_search.setMargin(new java.awt.Insets(2, 15, 2, 15));
        txt_search.setRound(35);
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(102, 102, 102));
        btn_search.setOpaque(true);
        btn_search.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_searchMouseMoved(evt);
            }
        });
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });

        btn_search4.setBackground(new java.awt.Color(102, 102, 102));
        btn_search4.setIcon(new javax.swing.ImageIcon("C:\\Users\\caoho\\Downloads\\searchic1.png")); // NOI18N
        btn_search4.setOpaque(true);
        btn_search4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_search4MouseMoved(evt);
            }
        });
        btn_search4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout title1Layout = new javax.swing.GroupLayout(title1);
        title1.setLayout(title1Layout);
        title1Layout.setHorizontalGroup(
            title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search4)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        title1Layout.setVerticalGroup(
            title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(title1Layout.createSequentialGroup()
                        .addGroup(title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_search4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        title3.setColorEnd(new java.awt.Color(102, 102, 102));
        title3.setColorStart(new java.awt.Color(102, 102, 102));
        title3.setPreferredSize(new java.awt.Dimension(900, 607));
        title3.setRoundBottomLeft(15);
        title3.setRoundBottomRight(15);
        title3.setRoundTopLeft(15);
        title3.setRoundTopRight(15);

        tbl_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_info);

        btn_load.setText("Load");
        btn_load.setColor1(new java.awt.Color(255, 51, 255));
        btn_load.setColor2(new java.awt.Color(255, 51, 51));
        btn_load.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_load.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_load.setIconTextGap(10);
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        lblHienthi6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi6.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi6.setText("Table Audit for update phone user");
        lblHienthi6.setFocusable(false);
        lblHienthi6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi6.setIconTextGap(10);

        javax.swing.GroupLayout title3Layout = new javax.swing.GroupLayout(title3);
        title3.setLayout(title3Layout);
        title3Layout.setHorizontalGroup(
            title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title3Layout.createSequentialGroup()
                        .addComponent(lblHienthi6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        title3Layout.setVerticalGroup(
            title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHienthi6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_quaLaiMain.setText("Quay lại form main");
        btn_quaLaiMain.setColor1(new java.awt.Color(255, 0, 102));
        btn_quaLaiMain.setColor2(new java.awt.Color(255, 153, 102));
        btn_quaLaiMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quaLaiMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quaLaiMain.setIconTextGap(10);
        btn_quaLaiMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaLaiMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_quaLaiMain, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_quaLaiMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 232, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        //        lblHienthi.setText(txt_search.getText());
    }//GEN-LAST:event_txt_searchKeyPressed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
//        String keySearch = txt_search.getText();
//        if (keySearch.trim().length() == 0) {
//            try {
//                loadTableFile();
//            } catch (SQLException ex) {
//                Logger.getLogger(frmMainManager.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else {
//            model.setRowCount(0);
//            for (File f : lFile) {
//                if (f.F_NAME.contains(keySearch)) {
//                    Object obj[] = {f.F_ID, f.F_NAME, f.F_TYPE, f.F_SIZE, f.F_DATECREATE, f.F_DATECHANGE, f.F_DESCRIPTION, f.F_PATH, f.F_ISDELETED};
//                    model.addRow(obj);
//                }
//            }
//        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        //        lblHienthi.setText(txt_search.getText());
    }//GEN-LAST:event_txt_searchKeyTyped

    private void btn_searchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseMoved
        // TODO add your handling code here:
        btn_search.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btn_searchMouseMoved

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        // TODO add your handling code here:
        btn_search.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_search4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search4MouseMoved
        // TODO add your handling code here:
        btn_search.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btn_search4MouseMoved

    private void btn_search4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search4MouseClicked
        String keySearch = txt_search.getText();
        if (keySearch.trim().length() == 0) {
            try {
                load();
            } catch (Exception ex) {
            }
        } else {
            model.setRowCount(0);
            for (AuditUpdateUser f : list) {
                if (f.getUNAME().contains(keySearch)) {           model.setRowCount(0);
                    Object obj[] = {f.getUNAME(), f.getDATE_UPDATE(), f.getIP_ADDRESS(), f.getCONTENT_UPDATE()};
                    model.addRow(obj);
                }
            }
        }
    }//GEN-LAST:event_btn_search4MouseClicked

    private void btn_search4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search4MouseExited
        // TODO add your handling code here:
        btn_search.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btn_search4MouseExited

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        load();
    }//GEN-LAST:event_btn_loadActionPerformed

    public void load()
    {
        String sql = "{call getAuditUser(?)}";
        try {
            CallableStatement cas = connection.prepareCall(sql);
            cas.registerOutParameter(1, OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);
            list.clear();
            model.setRowCount(0);
                model.setColumnIdentifiers(new Object[]{"OS_NAME", "DATE_UPDATE", "IP_ADDRESS", "CONTENT_UPDATE"});
            while (rs.next()) {
                Object obj[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                model.addRow(obj);
                list.add(new AuditUpdateUser(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)));
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null, "Bạn không có quyền thao tác", "Cảnh báo", JOptionPane.CANCEL_OPTION);
        }
    }
    private void btn_quaLaiMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaLaiMainActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quaLaiMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuditUseTrigger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuditUseTrigger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuditUseTrigger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuditUseTrigger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuditUseTrigger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_load;
    private swing.ButtonGradient btn_quaLaiMain;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel btn_search4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHienthi;
    private javax.swing.JLabel lblHienthi1;
    private javax.swing.JLabel lblHienthi6;
    private swing.PanelRound panelRound2;
    private javax.swing.JTable tbl_info;
    private swing.PanelRound title;
    private swing.PanelRound title1;
    private swing.PanelRound title2;
    private swing.PanelRound title3;
    private textfield.TextField txt_search;
    // End of variables declaration//GEN-END:variables
}
