/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlfile.FORM;

import Class.MahaFunction;
import Class.SYSConnection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.CallableStatement;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author caoho
 */
public class CreateUserWhiteProfile extends javax.swing.JFrame {
    private MahaFunction maha;
    public SYSConnection sysCon = new SYSConnection();
    public Connection con = sysCon.getConnection();
    /**
     * Creates new form CreateUserWhiteProfile
     */
    public CreateUserWhiteProfile() {
        initComponents();
        maha = new MahaFunction();
        loadComboboxProfile();
        loadComboboxUser();
        loadTableUserAndProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new swing.PanelRound();
        btn_taoUser = new swing.ButtonGradient();
        btn_xoaUser = new swing.ButtonGradient();
        btn_lamMoi = new swing.ButtonGradient();
        btn_quayLai = new swing.ButtonGradient();
        btn_capNhatProfiles = new swing.ButtonGradient();
        panelRound1 = new swing.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_profileUser = new javax.swing.JTable();
        txt_pass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbb_users = new javax.swing.JComboBox<>();
        cbb_profile = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tạo mới user với profile");

        panelRound2.setBackground(new java.awt.Color(0, 51, 51));
        panelRound2.setPreferredSize(new java.awt.Dimension(100, 720));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        btn_taoUser.setText("Tạo user");
        btn_taoUser.setColor1(new java.awt.Color(51, 255, 255));
        btn_taoUser.setColor2(new java.awt.Color(255, 0, 255));
        btn_taoUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_taoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoUserActionPerformed(evt);
            }
        });

        btn_xoaUser.setText("Xóa user");
        btn_xoaUser.setColor1(new java.awt.Color(255, 255, 51));
        btn_xoaUser.setColor2(new java.awt.Color(255, 102, 0));
        btn_xoaUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaUserActionPerformed(evt);
            }
        });

        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.setColor1(new java.awt.Color(51, 255, 255));
        btn_lamMoi.setColor2(new java.awt.Color(255, 0, 255));
        btn_lamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        btn_quayLai.setText("Quay lại");
        btn_quayLai.setColor1(new java.awt.Color(51, 255, 255));
        btn_quayLai.setColor2(new java.awt.Color(255, 0, 255));
        btn_quayLai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quayLaiActionPerformed(evt);
            }
        });

        btn_capNhatProfiles.setText("Cập nhật profile user");
        btn_capNhatProfiles.setToolTipText("");
        btn_capNhatProfiles.setColor1(new java.awt.Color(255, 0, 255));
        btn_capNhatProfiles.setColor2(new java.awt.Color(255, 102, 0));
        btn_capNhatProfiles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_capNhatProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatProfilesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_taoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_xoaUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_lamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_capNhatProfiles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_quayLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btn_taoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_xoaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_capNhatProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quayLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        tbl_profileUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_profileUser);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Các User hiện có");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên user (Tạo mới)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Profile");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mật khẩu");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbb_users, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbb_profile, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(txt_pass, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_users, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadComboboxUser()
    {
        
        String sql = "select * from dba_users";
        ResultSet rs = maha.ExeCuteQuery(sql);
        try {
            while(rs.next())
            {
                try {
                    cbb_users.addItem(rs.getString("USERNAME"));
                } catch (SQLException ex) {
                    Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadTableUserAndProfile()
    {
         try {
             String sql = "SELECT USERNAME, PROFILE FROM DBA_USERS";
             ResultSet rs = maha.ExeCuteQuery(sql);
             DefaultTableModel model = (DefaultTableModel) tbl_profileUser.getModel();
             model.setRowCount(0);
             model.setColumnIdentifiers(new Object[]{"USERNAME", "PROFILE"});
             while(rs.next())
             {
                 Object obj[] = {rs.getString("USERNAME"), rs.getString("PROFILE")};
                 model.addRow(obj);
             }} catch (SQLException ex) {
             Logger.getLogger(CreateProfileUser.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public void loadComboboxProfile()
    {
        String sql = "select profile from dba_profiles";
        ResultSet rs = maha.ExeCuteQuery(sql);
        try {
            while(rs.next())
            {
                try {
                    cbb_profile.addItem(rs.getString("PROFILE"));
                } catch (SQLException ex) {
                    Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void btn_taoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoUserActionPerformed
        String tenUser = txt_ten.getText();
        String passWord = txt_pass.getText();
        String tenProfile = (String)cbb_profile.getSelectedItem();
        
        if(tenUser.trim().length()<1 ||  passWord.trim().length()<1)
        {
            JOptionPane.showConfirmDialog(this, "Hãy điền đầy đủ vào các trường để tạo profile");
        }
        else
        {
            String sql = "{call sp_taouservoiprofile('"+tenUser+"','"+passWord+"','"+tenProfile+"')}";    
            try {
                CallableStatement call = con.prepareCall(sql);
                call.executeQuery();
                JOptionPane.showConfirmDialog(null, "Tạo thành công user "+tenUser+" với profile " + tenProfile, "Thông báo", JOptionPane.OK_OPTION);
                loadComboboxUser();
                loadTableUserAndProfile();
            } catch (SQLException ex) {
                Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showConfirmDialog(null, "Tạo thất bại, vui lòng kiểm tra các trường có chính xác không", "Thông báo", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_btn_taoUserActionPerformed

    private void btn_xoaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaUserActionPerformed
        
        String tenUser = (String)cbb_users.getSelectedItem();
        String sql = "call sp_xoaUser('"+tenUser+"')";
         if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa User: " + tenUser, "Xác nhận", JOptionPane.OK_CANCEL_OPTION, 
                 JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
            CallableStatement call;
             try {
                 call = con.prepareCall(sql);
                 call.executeQuery();
                 JOptionPane.showConfirmDialog(null, "Xóa thành công user " + tenUser, "Thông báo", JOptionPane.OK_OPTION);
                 loadComboboxUser();
                 loadTableUserAndProfile();
            } catch (SQLException ex) {
                Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showConfirmDialog(null, "Xóa thất bại user " + tenUser + ". Vui lòng kiểm tra lại thông tin", "Thông báo", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_btn_xoaUserActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        txt_ten.setText("");
        txt_pass.setText("");
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void btn_quayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quayLaiActionPerformed
        this.dispose();
//        CreateProfileUser u = new CreateProfileUser();
//        u.setVisible(true);
//        u.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_quayLaiActionPerformed

    private void btn_capNhatProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatProfilesActionPerformed
        String tenUser = (String)cbb_users.getSelectedItem();
        String tenProfile = (String)cbb_profile.getSelectedItem();
        String sql = "call sp_suaprofileuser('"+tenUser+"','"+tenProfile+"')";
        if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn cập nhật lại User: " + tenUser + ", với profile mới là "+ tenProfile,
                "Xác nhận", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
            CallableStatement call;
            try {
                call = con.prepareCall(sql);
                call.executeQuery();
                JOptionPane.showConfirmDialog(null, "Cập nhật thành công user " + tenUser, "Thông báo", JOptionPane.OK_OPTION);
                loadComboboxUser();
                loadTableUserAndProfile();
            } catch (SQLException ex) {
                Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showConfirmDialog(null, "Cập nhật thất bại user: " + tenUser + ". Vui lòng kiểm tra lại thông tin", "Thông báo",
                        JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_btn_capNhatProfilesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserWhiteProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUserWhiteProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_capNhatProfiles;
    private swing.ButtonGradient btn_lamMoi;
    private swing.ButtonGradient btn_quayLai;
    private swing.ButtonGradient btn_taoUser;
    private swing.ButtonGradient btn_xoaUser;
    private javax.swing.JComboBox<String> cbb_profile;
    private javax.swing.JComboBox<String> cbb_users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.PanelRound panelRound1;
    private swing.PanelRound panelRound2;
    private javax.swing.JTable tbl_profileUser;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
