/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package qlfile.FORM;


import Class.MahaFunction;
import Class.SYSConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caoho
 */
public class CreateProfileUser extends javax.swing.JFrame {
    private MahaFunction maha;
    
    public SYSConnection sysCon = new SYSConnection();
    public Connection con = sysCon.getConnection();
    /** Creates new form CreateProfileUser */
    public CreateProfileUser() {
        initComponents();
        loadProfile();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new swing.PanelRound();
        btn_taoProfile = new swing.ButtonGradient();
        btn_xoaProfile = new swing.ButtonGradient();
        btn_lamMoi = new swing.ButtonGradient();
        btn_quayLai = new swing.ButtonGradient();
        btn_taoUser = new swing.ButtonGradient();
        panelRound1 = new swing.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_profile = new javax.swing.JTable();
        txt_ten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_thoiGianSD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_soLanDoiPass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_soLanSaiMK = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_thoiGianKhoa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_soSession = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tạo profile");
        setPreferredSize(new java.awt.Dimension(1280, 690));

        panelRound2.setBackground(new java.awt.Color(0, 51, 51));
        panelRound2.setPreferredSize(new java.awt.Dimension(100, 720));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        btn_taoProfile.setText("Tạo profile");
        btn_taoProfile.setColor1(new java.awt.Color(51, 255, 255));
        btn_taoProfile.setColor2(new java.awt.Color(255, 0, 255));
        btn_taoProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_taoProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoProfileActionPerformed(evt);
            }
        });

        btn_xoaProfile.setText("Xóa profile");
        btn_xoaProfile.setColor1(new java.awt.Color(255, 255, 51));
        btn_xoaProfile.setColor2(new java.awt.Color(255, 102, 0));
        btn_xoaProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaProfileActionPerformed(evt);
            }
        });

        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.setColor1(new java.awt.Color(51, 255, 255));
        btn_lamMoi.setColor2(new java.awt.Color(255, 0, 255));
        btn_lamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        btn_quayLai.setText("Quay lại");
        btn_quayLai.setColor1(new java.awt.Color(255, 0, 255));
        btn_quayLai.setColor2(new java.awt.Color(255, 102, 0));
        btn_quayLai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quayLaiActionPerformed(evt);
            }
        });

        btn_taoUser.setText("Tạo user");
        btn_taoUser.setColor1(new java.awt.Color(51, 255, 255));
        btn_taoUser.setColor2(new java.awt.Color(255, 0, 255));
        btn_taoUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_taoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_taoProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_xoaProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
            .addComponent(btn_lamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_quayLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_taoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btn_taoProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_xoaProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quayLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_taoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        tbl_profile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_profile);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tên profile");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Thời gian sử dụng");

        txt_thoiGianSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_thoiGianSDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Số lần thay đổi password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Số lần được phép sai mật khẩu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Thời gian khóa khi sai mật khẩu");

        txt_thoiGianKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_thoiGianKhoaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Số session cho user");

        txt_soSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_thoiGianSD)
                                .addComponent(txt_ten)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_soLanDoiPass)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_thoiGianKhoa)
                                .addComponent(txt_soLanSaiMK)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                .addComponent(txt_soSession)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_thoiGianSD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_soLanDoiPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_soLanSaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_thoiGianKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_soSession, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadProfile()
    {
         try {
             String sql = "select * from dba_profiles";
             maha = new MahaFunction();
             ResultSet rs = maha.ExeCuteQuery(sql);
             DefaultTableModel model = (DefaultTableModel) tbl_profile.getModel();
             model.setRowCount(0);
             model.setColumnIdentifiers(new Object[]{"PROFILE", "RESOURCE_NAME", "RESOURC_TYPE", "LIMIT", "COMMON"});
             while(rs.next())
             {
                 Object obj[] = {rs.getString("PROFILE"), rs.getString("RESOURCE_NAME"), rs.getString("RESOURCE_TYPE"), rs.getString("LIMIT"), rs.getString("COMMON")};
                 model.addRow(obj);
             }} catch (SQLException ex) {
             Logger.getLogger(CreateProfileUser.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    private void txt_thoiGianSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_thoiGianSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_thoiGianSDActionPerformed

    private void txt_thoiGianKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_thoiGianKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_thoiGianKhoaActionPerformed

    private void btn_taoProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoProfileActionPerformed
        String tenProfile = txt_ten.getText();
        String thoiGianKhoa = txt_thoiGianKhoa.getText();
        String thoiGianSD = txt_thoiGianSD.getText();
        String soLanDoiPass = txt_soLanDoiPass.getText();
        String soLanSaiMatKhau = txt_soLanSaiMK.getText();
        String soSession = txt_soSession.getText();
        if(tenProfile.trim().length()<1 ||  thoiGianKhoa.trim().length()<1|| thoiGianSD.trim().length()<1||
                soLanDoiPass.trim().length()<1 || soLanSaiMatKhau.trim().length()<1)
        {
            JOptionPane.showConfirmDialog(this, "Hãy điền đầy đủ vào các trường để tạo profile");
        }
        else
        {
            try {
                CallableStatement callStatement = con.prepareCall("{call sp_taoProfile(?, ?, ?, ?, ?, ?)}");
                callStatement.setString(1, tenProfile);
                callStatement.setInt(2, Integer.parseInt(soSession));
                callStatement.setInt(3, Integer.parseInt(thoiGianSD));
                callStatement.setInt(4, Integer.parseInt(soLanDoiPass));
                callStatement.setInt(5, Integer.parseInt(soLanSaiMatKhau));
                callStatement.setInt(6, Integer.parseInt(thoiGianKhoa));
                callStatement.executeQuery();
                loadProfile();
                txt_ten.setText("");
                JOptionPane.showConfirmDialog(this, "Tạo mới profile: "+ tenProfile + " thành công", "Thông báo", 
                        JOptionPane.OK_OPTION);
            } catch (SQLException ex) {
                Logger.getLogger(CreateProfileUser.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showConfirmDialog(this, "Tạo thất bại, có thể do trùng tên profile, hãy thử với tên khác");
            }
        }
    }//GEN-LAST:event_btn_taoProfileActionPerformed

    private void txt_soSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soSessionActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        txt_ten.setText("");
        txt_thoiGianKhoa.setText("");
        txt_thoiGianSD.setText("");
        txt_soLanDoiPass.setText("");
        txt_soLanSaiMK.setText("");
        txt_soSession.setText("");
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void btn_xoaProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaProfileActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_profile.getModel();
        //getSelectedRow dùng để lấy ra vị trí dòng đang chọn trên table
        int dong = tbl_profile.getSelectedRow();
        String tenProfile = (String)model.getValueAt(dong, 0);
        if(tenProfile.trim().length() < 1)
        {
            //Dòng lệnh này chưa có hiệu lực
            JOptionPane.showConfirmDialog(null, "Vui lòng chọn tên profile trên bảng để xóa", "Thông báo", JOptionPane.OK_OPTION);
        }
        if(tenProfile.trim().length() > 0)
        {
            txt_ten.setText(tenProfile);
            if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa profile " + tenProfile, "Xác nhận", 
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
                try {
                    String sql = "{call  xoaprofile('" + tenProfile + "')}";
                    CallableStatement call = con.prepareCall(sql);
                    call.executeQuery();
                    JOptionPane.showConfirmDialog(null, "Xóa thành công profile " + tenProfile, "Thông báo", JOptionPane.OK_OPTION);
                    loadProfile();
                    call.close();
                } catch (SQLException ex) {
                    Logger.getLogger(CreateProfileUser.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showConfirmDialog(null, "Xóa thất bại", "Thông báo", JOptionPane.OK_OPTION);
                }
            }
        }
    }//GEN-LAST:event_btn_xoaProfileActionPerformed

    private void btn_taoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoUserActionPerformed
        // TODO add your handling code here:
        CreateUserWhiteProfile f = new CreateUserWhiteProfile();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_taoUserActionPerformed

    private void btn_quayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quayLaiActionPerformed
//        MainForm m = new MainForm();
//        m.setVisible(true);
//        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_quayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateProfileUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateProfileUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateProfileUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateProfileUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateProfileUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_lamMoi;
    private swing.ButtonGradient btn_quayLai;
    private swing.ButtonGradient btn_taoProfile;
    private swing.ButtonGradient btn_taoUser;
    private swing.ButtonGradient btn_xoaProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.PanelRound panelRound1;
    private swing.PanelRound panelRound2;
    private javax.swing.JTable tbl_profile;
    private javax.swing.JTextField txt_soLanDoiPass;
    private javax.swing.JTextField txt_soLanSaiMK;
    private javax.swing.JTextField txt_soSession;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_thoiGianKhoa;
    private javax.swing.JTextField txt_thoiGianSD;
    // End of variables declaration//GEN-END:variables

}
