/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlfile.FORM;
import java.sql.Connection;
import java.sql.DriverManager;
import Class.JDBCConnection;
import Class.SYSConnection;
import Class.UserSessionData;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.sql.Timestamp;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.CallableStatement;
import java.util.concurrent.ExecutionException;
import oracle.jdbc.OracleTypes;
import javax.swing.SwingWorker;
import java.awt.Color;

/**
 *
 * @author caoho
 */
public class frmMain extends javax.swing.JFrame {
    private JDBCConnection databaseConnection = new JDBCConnection();
    private SYSConnection sysConnection=new SYSConnection();
    private String username;
    private String password;
    
    private Connection connection;
    private Connection connection2;
    
    //    Phần mới thêm
    private String userNameIO, passWordIO;

    private frmMain() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    public void setUserNameIO(String userNameIO) {
        this.userNameIO = userNameIO;
    }

    public void setPassWordIO(String passWordIO) {
        this.passWordIO = passWordIO;
    }
    
    //    Hết phần mới thêm
    
    public frmMain(String userNameIO, String passWordIO) {
        connection = databaseConnection.getConnection();
        connection2=sysConnection.getConnection();
        initComponents();
        
//        Phần mới thêm
        this.userNameIO = userNameIO;
        this.passWordIO = passWordIO;
        this.username = userNameIO;
        this.password = passWordIO;
//        Hết phần mới thêm
        
        frmMain.CheckSessionWorker sessionWorker = new frmMain.CheckSessionWorker(this);
        sessionWorker.execute();
    }
    
    public void setUsername(String username) {
        this.username = username;
        lblHienthi.setText("Xin chào "+userNameIO +" !");
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public void setTime(String username){
//        this.username=username;
//        try {
//            Statement statement=connection2.createStatement();
//            ResultSet resultSet=statement.executeQuery("Select LAST_LOGIN FROM dba_users WHERE USERNAME='"+this.userNameIO.toUpperCase()+"'");            
//            while(resultSet.next()){
//                String lastLogin = resultSet.getString("LAST_LOGIN");
//                lbltime.setText("Lần cuối đăng nhập: "+lastLogin.toString());
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    
    private void initProcess(){
        ProcessForm PF=new ProcessForm();
        PF.setVisible(true);
        PF.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new swing.PanelRound();
        title = new swing.PanelRound();
        title2 = new swing.PanelRound();
        lblHienthi = new javax.swing.JLabel();
        btn_sgapga = new swing.ButtonGradient();
        btnDangxuat = new javax.swing.JLabel();
        btn_session = new swing.ButtonGradient();
        btn_tablespace = new swing.ButtonGradient();
        btn_quanLyUser = new swing.ButtonGradient();
        btn_4 = new swing.ButtonGradient();
        btn_5 = new swing.ButtonGradient();
        btn_audit = new swing.ButtonGradient();
        btn_profile = new swing.ButtonGradient();
        btn_6 = new swing.ButtonGradient();
        btn_session1 = new swing.ButtonGradient();
        btn_session2 = new swing.ButtonGradient();
        title1 = new swing.PanelRound();
        txt_search = new textfield.TextField();
        btn_search = new javax.swing.JLabel();
        title3 = new swing.PanelRound();
        btn_File = new swing.ButtonGradient();
        btn_Folders = new swing.ButtonGradient();
        btn_quanLyTaiKhoan = new swing.ButtonGradient();
        btn_a = new swing.ButtonGradient();
        title4 = new swing.PanelRound();
        lbltime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        panelRound2.setColorEnd(new java.awt.Color(0, 0, 0));
        panelRound2.setColorStart(new java.awt.Color(51, 51, 51));
        panelRound2.setPreferredSize(new java.awt.Dimension(1200, 690));

        title.setColorEnd(new java.awt.Color(102, 102, 102));
        title.setColorStart(new java.awt.Color(102, 102, 102));
        title.setRoundBottomLeft(15);
        title.setRoundBottomRight(15);
        title.setRoundTopLeft(15);
        title.setRoundTopRight(15);

        title2.setColorEnd(new java.awt.Color(0, 0, 0));
        title2.setColorStart(new java.awt.Color(51, 51, 51));
        title2.setRoundBottomLeft(15);
        title2.setRoundBottomRight(15);
        title2.setRoundTopLeft(15);
        title2.setRoundTopRight(15);

        lblHienthi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi.setText("User name");
        lblHienthi.setFocusable(false);
        lblHienthi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi.setIconTextGap(10);

        javax.swing.GroupLayout title2Layout = new javax.swing.GroupLayout(title2);
        title2.setLayout(title2Layout);
        title2Layout.setHorizontalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHienthi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        title2Layout.setVerticalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_sgapga.setText("SGA/PGA");
        btn_sgapga.setColor1(new java.awt.Color(0, 0, 255));
        btn_sgapga.setColor2(new java.awt.Color(0, 255, 204));
        btn_sgapga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sgapga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sgapga.setIconTextGap(10);
        btn_sgapga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sgapgaActionPerformed(evt);
            }
        });

        btnDangxuat.setBackground(new java.awt.Color(0, 0, 0));
        btnDangxuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangxuat.setForeground(new java.awt.Color(255, 204, 204));
        btnDangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.setIconTextGap(10);
        btnDangxuat.setOpaque(true);
        btnDangxuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDangxuatMouseMoved(evt);
            }
        });
        btnDangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangxuatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangxuatMouseExited(evt);
            }
        });

        btn_session.setText("Thông số session");
        btn_session.setColor1(new java.awt.Color(153, 0, 255));
        btn_session.setColor2(new java.awt.Color(0, 255, 204));
        btn_session.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_session.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_session.setIconTextGap(10);
        btn_session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sessionActionPerformed(evt);
            }
        });

        btn_tablespace.setText("Thông số tablespace");
        btn_tablespace.setColor1(new java.awt.Color(0, 0, 255));
        btn_tablespace.setColor2(new java.awt.Color(0, 255, 204));
        btn_tablespace.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tablespace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tablespace.setIconTextGap(10);
        btn_tablespace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tablespaceActionPerformed(evt);
            }
        });

        btn_quanLyUser.setText("Quản lý User");
        btn_quanLyUser.setColor1(new java.awt.Color(255, 0, 255));
        btn_quanLyUser.setColor2(new java.awt.Color(255, 0, 153));
        btn_quanLyUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quanLyUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyUser.setIconTextGap(10);
        btn_quanLyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyUserActionPerformed(evt);
            }
        });

        btn_4.setText("Policy");
        btn_4.setColor1(new java.awt.Color(0, 0, 255));
        btn_4.setColor2(new java.awt.Color(0, 255, 204));
        btn_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.setIconTextGap(10);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setText("Quản lý quyền User");
        btn_5.setColor1(new java.awt.Color(255, 0, 204));
        btn_5.setColor2(new java.awt.Color(0, 255, 204));
        btn_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.setIconTextGap(10);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_audit.setText("Audit");
        btn_audit.setColor1(new java.awt.Color(255, 0, 153));
        btn_audit.setColor2(new java.awt.Color(255, 102, 255));
        btn_audit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_audit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_audit.setIconTextGap(10);
        btn_audit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auditActionPerformed(evt);
            }
        });

        btn_profile.setText("Quản lý profile");
        btn_profile.setColor1(new java.awt.Color(0, 0, 255));
        btn_profile.setColor2(new java.awt.Color(0, 255, 204));
        btn_profile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_profile.setIconTextGap(10);
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        btn_6.setText("Quản lý nhóm quyền");
        btn_6.setColor1(new java.awt.Color(255, 0, 204));
        btn_6.setColor2(new java.awt.Color(0, 255, 204));
        btn_6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.setIconTextGap(10);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_session1.setText("Session đang hoạt động");
        btn_session1.setColor1(new java.awt.Color(153, 0, 255));
        btn_session1.setColor2(new java.awt.Color(0, 255, 204));
        btn_session1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_session1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_session1.setIconTextGap(10);
        btn_session1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_session1ActionPerformed(evt);
            }
        });

        btn_session2.setText("Thông tin process");
        btn_session2.setColor1(new java.awt.Color(153, 0, 255));
        btn_session2.setColor2(new java.awt.Color(0, 255, 204));
        btn_session2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_session2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_session2.setIconTextGap(10);
        btn_session2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_session2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_audit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_quanLyUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tablespace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sgapga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_session1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_session2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_sgapga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_session1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_session2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tablespace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanLyUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_audit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        title1.setColorEnd(new java.awt.Color(102, 102, 102));
        title1.setColorStart(new java.awt.Color(102, 102, 102));
        title1.setPreferredSize(new java.awt.Dimension(900, 50));
        title1.setRoundBottomLeft(15);
        title1.setRoundBottomRight(15);
        title1.setRoundTopLeft(15);
        title1.setRoundTopRight(15);

        txt_search.setForeground(new java.awt.Color(0, 204, 204));
        txt_search.setCaretColor(new java.awt.Color(0, 153, 153));
        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_search.setMargin(new java.awt.Insets(2, 15, 2, 15));
        txt_search.setRound(35);
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(102, 102, 102));
        btn_search.setOpaque(true);
        btn_search.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_searchMouseMoved(evt);
            }
        });
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout title1Layout = new javax.swing.GroupLayout(title1);
        title1.setLayout(title1Layout);
        title1Layout.setHorizontalGroup(
            title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        title1Layout.setVerticalGroup(
            title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(title1Layout.createSequentialGroup()
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        title3.setColorEnd(new java.awt.Color(102, 102, 102));
        title3.setColorStart(new java.awt.Color(102, 102, 102));
        title3.setPreferredSize(new java.awt.Dimension(900, 607));
        title3.setRoundBottomLeft(15);
        title3.setRoundBottomRight(15);
        title3.setRoundTopLeft(15);
        title3.setRoundTopRight(15);

        btn_File.setText("Quản lí Files");
        btn_File.setColor1(new java.awt.Color(153, 0, 255));
        btn_File.setColor2(new java.awt.Color(0, 255, 204));
        btn_File.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_File.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_File.setIconTextGap(10);
        btn_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FileActionPerformed(evt);
            }
        });

        btn_Folders.setText("Quản lí Folders");
        btn_Folders.setColor1(new java.awt.Color(153, 0, 255));
        btn_Folders.setColor2(new java.awt.Color(0, 255, 204));
        btn_Folders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Folders.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Folders.setIconTextGap(10);
        btn_Folders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FoldersActionPerformed(evt);
            }
        });

        btn_quanLyTaiKhoan.setText("Quản lý tài khoản");
        btn_quanLyTaiKhoan.setColor1(new java.awt.Color(255, 0, 153));
        btn_quanLyTaiKhoan.setColor2(new java.awt.Color(204, 0, 204));
        btn_quanLyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quanLyTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyTaiKhoan.setIconTextGap(10);
        btn_quanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyTaiKhoanActionPerformed(evt);
            }
        });

        btn_a.setText("Xem Trigger Logon");
        btn_a.setColor1(new java.awt.Color(153, 0, 255));
        btn_a.setColor2(new java.awt.Color(0, 255, 204));
        btn_a.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_a.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_a.setIconTextGap(10);
        btn_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout title3Layout = new javax.swing.GroupLayout(title3);
        title3.setLayout(title3Layout);
        title3Layout.setHorizontalGroup(
            title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_File, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Folders, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(btn_quanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(btn_a, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        title3Layout.setVerticalGroup(
            title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_File, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Folders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        title4.setColorEnd(new java.awt.Color(102, 102, 102));
        title4.setColorStart(new java.awt.Color(102, 102, 102));
        title4.setPreferredSize(new java.awt.Dimension(900, 607));
        title4.setRoundBottomLeft(15);
        title4.setRoundBottomRight(15);
        title4.setRoundTopLeft(15);
        title4.setRoundTopRight(15);

        javax.swing.GroupLayout title4Layout = new javax.swing.GroupLayout(title4);
        title4.setLayout(title4Layout);
        title4Layout.setHorizontalGroup(
            title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        title4Layout.setVerticalGroup(
            title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        lbltime.setBackground(new java.awt.Color(255, 0, 51));
        lbltime.setForeground(new java.awt.Color(255, 0, 51));
        lbltime.setText("jLabel1");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(lbltime)
                        .addGap(235, 235, 235))))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 632, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(lbltime)
                        .addGap(24, 24, 24))))
        );

        getContentPane().add(panelRound2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private static class CheckSessionWorker extends SwingWorker<Boolean, Void>{
        private final frmMain mainform;
        
        public CheckSessionWorker(frmMain mainform){
            this.mainform=mainform;
        }

        @Override
        protected Boolean doInBackground() throws Exception {
            String url = "jdbc:oracle:thin:@:1521:orcl";
            String username = "sys as sysdba";
            String password = "sys";
            boolean sessionExists = true;
            
            try (Connection connection3 = DriverManager.getConnection(url, username, password)) {
                while (sessionExists) {
                    try (CallableStatement cal = connection3.prepareCall("{call check_session(?, ?)}")) {
                        String currentUsername = mainform.username;
                        cal.setString(1, currentUsername.toUpperCase());
                        cal.registerOutParameter(2, OracleTypes.NUMBER);
                        cal.execute();
                        int sessionExistsNumber = cal.getInt(2);
                        sessionExists = (sessionExistsNumber == 1);//1
                        
                        cal.close();
                    }
                    Thread.sleep(1000);
                }
                return sessionExists;
            } catch (Exception e) {                
                e.printStackTrace();
                return false;
            }
        }
        
        @Override
        protected void done() {
            try {
                boolean sessionValid=get();
                if (!sessionValid) {
                    // Nếu session không tồn tại, đóng form và thoát ứng dụng
                    mainform.dispose();
                    System.exit(0);
                } else {
                    System.out.println("QLFIle.MainForm.CheckSessionWorker.done()");
                }
                
            } catch (InterruptedException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }
    
    private void SessionMethod() {
        try {
            Statement statement = connection2.createStatement();
            connection.close();
            //Tránh việc 2 connection cùng hiển thị thông tin
            ResultSet resultSet = statement.executeQuery("SELECT * FROM v$session where username='PROJECT'");
            while(resultSet.next()){            
                String sid=resultSet.getString("SID");
                String serial=resultSet.getString("SERIAL#");
                String username=resultSet.getString("USERNAME");
                String program=resultSet.getString("PROGRAM");
                
                String message = String.format("SID: %s%nSERIAL: %s%nUSERNAME: %s%nPROGRAM: %s", sid, serial, username, program);
                JOptionPane.showMessageDialog(null, message);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            sysConnection.closeConnection();
        }
    }
    
    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btnDangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangxuatMouseExited
        btnDangxuat.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btnDangxuatMouseExited

    private void btnDangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangxuatMouseClicked
        try {
            CallableStatement disconnectProc = connection2.prepareCall("{call kill_user_sessions(?)}");
            disconnectProc.setString(1, userNameIO.toUpperCase());
            disconnectProc.execute();
            disconnectProc.close();

            connection2.close();
            connection2.close();
            connection2.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to close connection. Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDangxuatMouseClicked

    private void btnDangxuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangxuatMouseMoved
        // TODO add your handling code here:
        btnDangxuat.setBackground(new Color(221, 21, 83));
        //        btnDangxuat.setForeground(Color.white);
    }//GEN-LAST:event_btnDangxuatMouseMoved

    private void btn_sgapgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sgapgaActionPerformed
        InfomationSGAPGA information=new InfomationSGAPGA();
        information.setVisible(true);
        information.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_sgapgaActionPerformed

    private void btn_sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sessionActionPerformed
        SessionMethod();
    }//GEN-LAST:event_btn_sessionActionPerformed

    private void btn_tablespaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tablespaceActionPerformed
        DataspaceForm data=new DataspaceForm();
        data.setVisible(true);
        data.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_tablespaceActionPerformed

    private void btn_quanLyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyUserActionPerformed
        UserInformation userframe=new UserInformation();
        userframe.setVisible(true);
        userframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_quanLyUserActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        PolicyForm policyframe=new PolicyForm();
        policyframe.setVisible(true);
        policyframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        GrantUserForm grantuserform=new GrantUserForm();
        grantuserform.setVisible(true);
        grantuserform.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_auditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auditActionPerformed
        AuditForm auditframe=new AuditForm();
        auditframe.setVisible(true);
        auditframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_auditActionPerformed

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        CreateProfileUser u = new CreateProfileUser();
        u.setVisible(true);
        u.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        // TODO add your handling code here:
        btn_search.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_searchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseMoved
        // TODO add your handling code here:
        btn_search.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btn_searchMouseMoved

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        NhomQuyenForm nhomquyenform=new NhomQuyenForm();
        nhomquyenform.setVisible(true);
        nhomquyenform.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_session1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_session1ActionPerformed
        KillsessionForm killform=new KillsessionForm();
       killform.setVisible(true);
       killform.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_session1ActionPerformed

    private void btn_session2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_session2ActionPerformed
        initProcess();
    }//GEN-LAST:event_btn_session2ActionPerformed

    private void btn_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FileActionPerformed
        CRUD_FileForm crudFileForm = new CRUD_FileForm();
        crudFileForm.setUsernameAndPassword(username, password);
        crudFileForm.setVisible(true);
        crudFileForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_FileActionPerformed

    private void btn_FoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FoldersActionPerformed
        CRUD_FolderForm crudFolderForm = new CRUD_FolderForm();
        crudFolderForm.setUsernameAndPassword(username, password);
        crudFolderForm.setVisible(true);
        crudFolderForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_FoldersActionPerformed

    private void btn_quanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyTaiKhoanActionPerformed
        frmMainManager mf = new frmMainManager(userNameIO, passWordIO);
        mf.setVisible(true);
        mf.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_quanLyTaiKhoanActionPerformed

    private void btn_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aActionPerformed
        // TODO add your handling code here:
        LogOnTrigger a = new LogOnTrigger(userNameIO, passWordIO);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDangxuat;
    private swing.ButtonGradient btn_4;
    private swing.ButtonGradient btn_5;
    private swing.ButtonGradient btn_6;
    private swing.ButtonGradient btn_File;
    private swing.ButtonGradient btn_Folders;
    private swing.ButtonGradient btn_a;
    private swing.ButtonGradient btn_audit;
    private swing.ButtonGradient btn_profile;
    private swing.ButtonGradient btn_quanLyTaiKhoan;
    private swing.ButtonGradient btn_quanLyUser;
    private javax.swing.JLabel btn_search;
    private swing.ButtonGradient btn_session;
    private swing.ButtonGradient btn_session1;
    private swing.ButtonGradient btn_session2;
    private swing.ButtonGradient btn_sgapga;
    private swing.ButtonGradient btn_tablespace;
    private javax.swing.JLabel lblHienthi;
    private javax.swing.JLabel lbltime;
    private swing.PanelRound panelRound2;
    private swing.PanelRound title;
    private swing.PanelRound title1;
    private swing.PanelRound title2;
    private swing.PanelRound title3;
    private swing.PanelRound title4;
    private textfield.TextField txt_search;
    // End of variables declaration//GEN-END:variables
}
