/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlfile.FORM;

import Class.MahaFunction;
import Class.SYSConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author caoho
 */
public class InfomationSGAPGA extends javax.swing.JFrame {

    private SYSConnection sysConnection=new SYSConnection();
    private Connection connection2;
    private MahaFunction maha;
    
    public InfomationSGAPGA() {
        initComponents();
        maha = new MahaFunction();
        connection2 = sysConnection.getConnection();
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new swing.PanelRound();
        panelRound3 = new swing.PanelRound();
        btn_sga = new swing.ButtonGradient();
        btn_pga = new swing.ButtonGradient();
        btn_process = new swing.ButtonGradient();
        btn_instance = new swing.ButtonGradient();
        btn_database = new swing.ButtonGradient();
        title2 = new swing.PanelRound();
        lblHienthi1 = new javax.swing.JLabel();
        lblHienthi = new javax.swing.JLabel();
        btn_controlfiles = new swing.ButtonGradient();
        btn_datafile = new swing.ButtonGradient();
        btn_spfile = new swing.ButtonGradient();
        panelRound1 = new swing.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Countries = new javax.swing.JTable();
        btn_quaLaiMain = new swing.ButtonGradient();
        lblHienthi2 = new javax.swing.JLabel();
        lblHienthi3 = new javax.swing.JLabel();
        lbltuyChon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xem một số thông tin tùy chọn");
        setPreferredSize(new java.awt.Dimension(1200, 690));

        panelRound2.setColorEnd(new java.awt.Color(0, 0, 0));
        panelRound2.setColorStart(new java.awt.Color(51, 51, 51));
        panelRound2.setPreferredSize(new java.awt.Dimension(1200, 690));

        panelRound3.setBackground(new java.awt.Color(0, 51, 51));
        panelRound3.setPreferredSize(new java.awt.Dimension(100, 720));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        btn_sga.setText("SGA");
        btn_sga.setColor1(new java.awt.Color(51, 255, 255));
        btn_sga.setColor2(new java.awt.Color(255, 0, 255));
        btn_sga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sgaActionPerformed(evt);
            }
        });

        btn_pga.setText("PGA");
        btn_pga.setColor1(new java.awt.Color(255, 255, 51));
        btn_pga.setColor2(new java.awt.Color(255, 102, 0));
        btn_pga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_pga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pgaActionPerformed(evt);
            }
        });

        btn_process.setText("PROCESS");
        btn_process.setColor1(new java.awt.Color(51, 255, 255));
        btn_process.setColor2(new java.awt.Color(255, 0, 255));
        btn_process.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processActionPerformed(evt);
            }
        });

        btn_instance.setText("INSTANCE");
        btn_instance.setColor1(new java.awt.Color(255, 0, 255));
        btn_instance.setColor2(new java.awt.Color(255, 102, 0));
        btn_instance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_instance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_instanceActionPerformed(evt);
            }
        });

        btn_database.setText("DATABASE");
        btn_database.setColor1(new java.awt.Color(51, 255, 255));
        btn_database.setColor2(new java.awt.Color(255, 0, 255));
        btn_database.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_databaseActionPerformed(evt);
            }
        });

        title2.setColorEnd(new java.awt.Color(0, 102, 102));
        title2.setColorStart(new java.awt.Color(102, 0, 102));
        title2.setRoundBottomLeft(15);
        title2.setRoundBottomRight(15);
        title2.setRoundTopLeft(15);
        title2.setRoundTopRight(15);

        lblHienthi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi1.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUser.png"))); // NOI18N
        lblHienthi1.setFocusable(false);
        lblHienthi1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi1.setIconTextGap(10);

        lblHienthi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi.setText("Sys as sysdba");
        lblHienthi.setFocusable(false);
        lblHienthi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi.setIconTextGap(10);

        javax.swing.GroupLayout title2Layout = new javax.swing.GroupLayout(title2);
        title2.setLayout(title2Layout);
        title2Layout.setHorizontalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHienthi)
                    .addComponent(lblHienthi1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        title2Layout.setVerticalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHienthi1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHienthi)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btn_controlfiles.setText("CONTROLFILE");
        btn_controlfiles.setColor1(new java.awt.Color(255, 255, 51));
        btn_controlfiles.setColor2(new java.awt.Color(255, 102, 0));
        btn_controlfiles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_controlfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_controlfilesActionPerformed(evt);
            }
        });

        btn_datafile.setText("DATAFILE");
        btn_datafile.setColor1(new java.awt.Color(255, 0, 255));
        btn_datafile.setColor2(new java.awt.Color(255, 102, 0));
        btn_datafile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_datafile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datafileActionPerformed(evt);
            }
        });

        btn_spfile.setText("SPFILE");
        btn_spfile.setColor1(new java.awt.Color(51, 255, 255));
        btn_spfile.setColor2(new java.awt.Color(255, 0, 255));
        btn_spfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_spfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_spfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_database, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_instance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_process, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pga, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(btn_sga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_controlfiles, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(btn_spfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_datafile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btn_sga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_process, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_instance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_database, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_datafile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_controlfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_spfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        tb_Countries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_Countries);

        btn_quaLaiMain.setText("Quay lại form main");
        btn_quaLaiMain.setColor1(new java.awt.Color(255, 0, 102));
        btn_quaLaiMain.setColor2(new java.awt.Color(255, 153, 102));
        btn_quaLaiMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quaLaiMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quaLaiMain.setIconTextGap(10);
        btn_quaLaiMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaLaiMainActionPerformed(evt);
            }
        });

        lblHienthi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi2.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi2.setText("Sys as sysdba");
        lblHienthi2.setFocusable(false);
        lblHienthi2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi2.setIconTextGap(10);

        lblHienthi3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi3.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi3.setText("Bảng thông tin tùy chọn");
        lblHienthi3.setFocusable(false);
        lblHienthi3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi3.setIconTextGap(10);

        lbltuyChon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltuyChon.setForeground(new java.awt.Color(255, 255, 255));
        lbltuyChon.setFocusable(false);
        lbltuyChon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbltuyChon.setIconTextGap(10);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_quaLaiMain, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(lblHienthi3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltuyChon)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound1Layout.createSequentialGroup()
                    .addGap(478, 478, 478)
                    .addComponent(lblHienthi2)
                    .addContainerGap(478, Short.MAX_VALUE)))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHienthi3)
                    .addComponent(lbltuyChon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quaLaiMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound1Layout.createSequentialGroup()
                    .addGap(329, 329, 329)
                    .addComponent(lblHienthi2)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1254, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_quaLaiMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaLaiMainActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quaLaiMainActionPerformed

    private void btn_sgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sgaActionPerformed
                String sql = "{call getSGA(?)}";
                lbltuyChon.setText("SGA");
        try {
            CallableStatement cas = connection2.prepareCall(sql);
            cas.registerOutParameter(1, OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);

            DefaultTableModel model =(DefaultTableModel) tb_Countries.getModel();
            //          Xóa toàn bộ dòng
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{
            "Name", "Value", "Con_ID"
            });
            while(rs.next())
            {
                Object obj[] = {rs.getString(1),rs.getString(2), rs.getString(3)};
                model.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_sgaActionPerformed

    private void btn_pgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pgaActionPerformed
       SYSConnection kn = new SYSConnection();
        Connection conn = kn.getConnection();
        lbltuyChon.setText("PGA");
        String sql = "{call getPGA(?)}";
        try {
            CallableStatement cas = conn.prepareCall(sql);
            cas.registerOutParameter(1, OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);
            DefaultTableModel model =(DefaultTableModel) tb_Countries.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"Name", "Value", "Unit", "CON_ID"});
            while(rs.next())
            {
                Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                model.addRow(obj);
            }

        } catch (SQLException ex) {
            Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_pgaActionPerformed

    private void btn_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processActionPerformed
        String sql = "{call getProcess(?)}";
        lbltuyChon.setText("PROCESS");
        try {
            CallableStatement cas = connection2.prepareCall(sql);
            cas.registerOutParameter(1,OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);

            DefaultTableModel model =(DefaultTableModel) tb_Countries.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"ADDR", "PID", "SOSID", "SPID","STID", "Execution_type", "Pname","UserName","Serial", "Termenal"});
            while(rs.next())
            {
                Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4), rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)};
                model.addRow(obj);
            }

        } catch (SQLException ex) {
            Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_processActionPerformed

    private void btn_instanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_instanceActionPerformed
        String sql = "{call getInstance(?)}";
        lbltuyChon.setText("INSTANCE");
        try {
            CallableStatement cas = connection2.prepareCall(sql);
            cas.registerOutParameter(1,OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);

            DefaultTableModel model =(DefaultTableModel) tb_Countries.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"Instance_number", "Instance_name", "Host_name", "Version", "Startup_time", "Status"});
            while(rs.next())
            {
                Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                model.addRow(obj);
            }

        } catch (SQLException ex) {
            Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_instanceActionPerformed

    private void btn_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_databaseActionPerformed
        String sql = "{call getDatabase(?)}";
        lbltuyChon.setText("DATABASE");
        try {
            CallableStatement cas = connection2.prepareCall(sql);
            cas.registerOutParameter(1,OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);

            DefaultTableModel model =(DefaultTableModel) tb_Countries.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"BDID", "Name", "Created", "Resetlogs_change","Resetlogs_Time", "Prior_resetlogs_change"});
            while(rs.next())
            {
                Object obj[] = {rs.getString(1),rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5),rs.getString(6)};
                model.addRow(obj);
            }

        } catch (SQLException ex) {
            Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_databaseActionPerformed

    private void btn_controlfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_controlfilesActionPerformed
        String sql = "{call getControlfile(?)}";
        lbltuyChon.setText("CONTROLFILE");
        try {
            CallableStatement cas = connection2.prepareCall(sql);
            cas.registerOutParameter(1,OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);

            DefaultTableModel model =(DefaultTableModel) tb_Countries.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"Status", "Name", "Is_recovery_dest_file", "Block_size", "File_Size_BLKS", "Con_ID"});
            while(rs.next())
            {
                Object obj[] = {rs.getString(1),rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5),rs.getString(6)};
                model.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_controlfilesActionPerformed

    private void btn_datafileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datafileActionPerformed
        String sql = "{call getDatafile(?)}";
        lbltuyChon.setText("DATAFILE");
        try {
            CallableStatement cas = connection2.prepareCall(sql);
            cas.registerOutParameter(1,OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);

            DefaultTableModel model =(DefaultTableModel) tb_Countries.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"File", "Creation_change", "Creation_time", "TS", "Rfile", "Status", "Enable", "Checkpoint_change", "CheckPoint_Time", "Name", "Block_size"});
            while(rs.next())
            {
                Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(21),rs.getString(20)};
                model.addRow(obj);
            }

        } catch (SQLException ex) {
            Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_datafileActionPerformed

    private void btn_spfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_spfileActionPerformed
       String sql = "{call getFilestat(?)}";
       lbltuyChon.setText("SPFILE");
        try{
            CallableStatement cas = connection2.prepareCall(sql);
            cas.registerOutParameter(1,OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);
        DefaultTableModel model = (DefaultTableModel) tb_Countries.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"FILE","PHYRDS","PHYWRTS","PHYBLKWRT"});
        try {
            while(rs.next())
            {
                try {
                    Object obj[] = {rs.getString("file#"), rs.getString("PHYRDS"), rs.getString("PHYWRTS"), rs.getString("PHYBLKWRT")};
                    model.addRow(obj);
                } catch (SQLException ex) {
                    Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(InfomationSGAPGA.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btn_spfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfomationSGAPGA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfomationSGAPGA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfomationSGAPGA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfomationSGAPGA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfomationSGAPGA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_controlfiles;
    private swing.ButtonGradient btn_database;
    private swing.ButtonGradient btn_datafile;
    private swing.ButtonGradient btn_instance;
    private swing.ButtonGradient btn_pga;
    private swing.ButtonGradient btn_process;
    private swing.ButtonGradient btn_quaLaiMain;
    private swing.ButtonGradient btn_sga;
    private swing.ButtonGradient btn_spfile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHienthi;
    private javax.swing.JLabel lblHienthi1;
    private javax.swing.JLabel lblHienthi2;
    private javax.swing.JLabel lblHienthi3;
    private javax.swing.JLabel lbltuyChon;
    private swing.PanelRound panelRound1;
    private swing.PanelRound panelRound2;
    private swing.PanelRound panelRound3;
    private javax.swing.JTable tb_Countries;
    private swing.PanelRound title2;
    // End of variables declaration//GEN-END:variables
}
