
package qlfile.FORM;

/**
 *
 * @author caoho
 * 
 */
import Class.JDBCConnection;
import Class.SYSConnection;
import java.beans.Statement;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;
import java.sql.ResultSet;


public class LogOnTrigger extends javax.swing.JFrame {

     private String userNameIO, passWordIO;

    private LogOnTrigger() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    public void setUserNameIO(String userNameIO) {
        this.userNameIO = userNameIO;
    }

    public void setPassWordIO(String passWordIO) {
        this.passWordIO = passWordIO;
    }
    
    //    Hết phần mới thêm
//    LoginForm frmlogin = new LoginForm();
    
    
    private JDBCConnection databaseConnection = new JDBCConnection();
    private SYSConnection sysConnection=new SYSConnection();
    public Connection connection;
    
    DefaultTableModel model;
    
    public LogOnTrigger(String userNameIO, String passWordIO) {
        initComponents();
        this.userNameIO = userNameIO;
        this.passWordIO = passWordIO;
//        connection = databaseConnection.getConnection(userNameIO, passWordIO);
        connection = databaseConnection.getConnection("mindfulness", "123");
        model  = (DefaultTableModel) tb_Countries1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound3 = new swing.PanelRound();
        btn_con = new swing.ButtonGradient();
        btn_hienThi = new swing.ButtonGradient();
        btn_disc = new swing.ButtonGradient();
        title2 = new swing.PanelRound();
        lblHienthi1 = new javax.swing.JLabel();
        lblHienthi = new javax.swing.JLabel();
        panelRound2 = new swing.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Countries1 = new javax.swing.JTable();
        btn_quaLaiMain1 = new swing.ButtonGradient();
        lblHienthi2 = new javax.swing.JLabel();
        lblHienthi3 = new javax.swing.JLabel();
        lbltuyChon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound3.setBackground(new java.awt.Color(0, 51, 51));
        panelRound3.setPreferredSize(new java.awt.Dimension(100, 720));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        btn_con.setText("Kết nối");
        btn_con.setColor1(new java.awt.Color(51, 255, 255));
        btn_con.setColor2(new java.awt.Color(255, 0, 255));
        btn_con.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conActionPerformed(evt);
            }
        });

        btn_hienThi.setText("Hiển thị");
        btn_hienThi.setColor1(new java.awt.Color(255, 255, 51));
        btn_hienThi.setColor2(new java.awt.Color(255, 102, 0));
        btn_hienThi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hienThiActionPerformed(evt);
            }
        });

        btn_disc.setText("Ngắt kết nối");
        btn_disc.setColor1(new java.awt.Color(255, 0, 255));
        btn_disc.setColor2(new java.awt.Color(255, 102, 0));
        btn_disc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_discActionPerformed(evt);
            }
        });

        title2.setColorEnd(new java.awt.Color(0, 102, 102));
        title2.setColorStart(new java.awt.Color(102, 0, 102));
        title2.setRoundBottomLeft(15);
        title2.setRoundBottomRight(15);
        title2.setRoundTopLeft(15);
        title2.setRoundTopRight(15);

        lblHienthi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi1.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUser.png"))); // NOI18N
        lblHienthi1.setFocusable(false);
        lblHienthi1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi1.setIconTextGap(10);

        lblHienthi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi.setText("Mindfulness");
        lblHienthi.setFocusable(false);
        lblHienthi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi.setIconTextGap(10);

        javax.swing.GroupLayout title2Layout = new javax.swing.GroupLayout(title2);
        title2.setLayout(title2Layout);
        title2Layout.setHorizontalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHienthi1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(title2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblHienthi)))
                .addGap(22, 22, 22))
        );
        title2Layout.setVerticalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHienthi1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHienthi)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_disc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(btn_con, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btn_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_disc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        tb_Countries1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_Countries1);

        btn_quaLaiMain1.setText("Quay lại form main");
        btn_quaLaiMain1.setColor1(new java.awt.Color(255, 0, 102));
        btn_quaLaiMain1.setColor2(new java.awt.Color(255, 153, 102));
        btn_quaLaiMain1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quaLaiMain1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quaLaiMain1.setIconTextGap(10);
        btn_quaLaiMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaLaiMain1ActionPerformed(evt);
            }
        });

        lblHienthi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi2.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi2.setText("Sys as sysdba");
        lblHienthi2.setFocusable(false);
        lblHienthi2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi2.setIconTextGap(10);

        lblHienthi3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi3.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi3.setText("Ghi nhận ngắt kết nối");
        lblHienthi3.setFocusable(false);
        lblHienthi3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi3.setIconTextGap(10);

        lbltuyChon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltuyChon.setForeground(new java.awt.Color(255, 255, 255));
        lbltuyChon.setFocusable(false);
        lbltuyChon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbltuyChon.setIconTextGap(10);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_quaLaiMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(lblHienthi3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltuyChon)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound2Layout.createSequentialGroup()
                    .addGap(478, 478, 478)
                    .addComponent(lblHienthi2)
                    .addContainerGap(478, Short.MAX_VALUE)))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHienthi3)
                    .addComponent(lbltuyChon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quaLaiMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound2Layout.createSequentialGroup()
                    .addGap(329, 329, 329)
                    .addComponent(lblHienthi2)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conActionPerformed
        String sql = "conn mindfulness / 123";
        try {
            Statement st = (Statement) connection.createStatement();
            st.execute();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_conActionPerformed

    private void btn_hienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hienThiActionPerformed
        lbltuyChon.setText("Trigger");
        String sql = "{call getTrigger(?)}";
        try {
            CallableStatement cas = connection.prepareCall(sql);
            cas.registerOutParameter(1, OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);
            model =(DefaultTableModel) tb_Countries1.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"u_id", "u_date", "action"});
            while(rs.next())
            {
                Object obj[] = {rs.getString(1),rs.getString(2),rs.getString(3)};
                model.addRow(obj);
            }

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_hienThiActionPerformed

    private void btn_discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_discActionPerformed
        String sql = "disc";
        lbltuyChon.setText("INSTANCE");
        try {
            Statement st = (Statement) connection.createStatement();
            st.execute();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_discActionPerformed

    private void btn_quaLaiMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaLaiMain1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quaLaiMain1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOnTrigger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOnTrigger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOnTrigger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOnTrigger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogOnTrigger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_con;
    private swing.ButtonGradient btn_disc;
    private swing.ButtonGradient btn_hienThi;
    private swing.ButtonGradient btn_quaLaiMain1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHienthi;
    private javax.swing.JLabel lblHienthi1;
    private javax.swing.JLabel lblHienthi2;
    private javax.swing.JLabel lblHienthi3;
    private javax.swing.JLabel lbltuyChon;
    private swing.PanelRound panelRound2;
    private swing.PanelRound panelRound3;
    private javax.swing.JTable tb_Countries1;
    private swing.PanelRound title2;
    // End of variables declaration//GEN-END:variables
}
