/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlfile.FORM;

//import Class.File;
import Class.JDBCConnection;
import Class.User;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.CallableStatement;
import oracle.jdbc.OracleTypes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author caoho
 */
public class ManagerIO extends javax.swing.JFrame {

    private DefaultTableModel model;
    private List<User> lUser;
    private JDBCConnection getConnect = new JDBCConnection();
    private Connection connect;
    public String userNameIO, passWordIO;
    private String filePath;
    private int viTri;

    private ManagerIO() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void setUserNameIO(String userNameIO) {
        this.userNameIO = userNameIO;
    }

    public void setPassWordIO(String passWordIO) {
        this.passWordIO = passWordIO;
    }


    public ManagerIO(String userNameIO, String passWordIO){
        
        initComponents();
        this.userNameIO = userNameIO;
        this.passWordIO = passWordIO;
        connect = (Connection) getConnect.getConnection(userNameIO, passWordIO);
        lUser = new ArrayList<>();
        this.setLocationRelativeTo(null);
        setUsername();
        model = (DefaultTableModel) tbl_info.getModel();
        loadUser();
    }
    
    public void setUsername() {
        lblHienthi.setText(userNameIO);
    }

    public void loadUser(){
        String sql = "{call getUserInfomation(?)}";
        try {
            CallableStatement cas = connect.prepareCall(sql);
            cas.registerOutParameter(1, OracleTypes.CURSOR);
            cas.executeQuery();
            ResultSet rs = (ResultSet) cas.getObject(1);
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"U_ID", "U_NAME", "U_PHONE", "U_IMAGAE"});
            lUser.clear();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
                lUser.add(new User(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)));
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Bạn không có quyền thao tác ", "Cảnh báo", JOptionPane.CANCEL_OPTION);
//            this.dispose();
        }
    }

//    public void loadUser() {
////        readWriteList();
//        if (lUser.isEmpty() == false) {
//            for (User user : lUser) {
//                model.addRow(new Object[]{user.getU_id(), user.getU_name(), user.getU_phone(), user.getU_image().toString()});
//            }
//        } else {
//            JOptionPane.showConfirmDialog(null, "Bạn không có quyền thao tác ", "Cảnh báo", JOptionPane.CANCEL_OPTION);
//            System.exit(0);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new swing.PanelRound();
        title = new swing.PanelRound();
        title2 = new swing.PanelRound();
        lblHienthi1 = new javax.swing.JLabel();
        lblHienthi = new javax.swing.JLabel();
        btn_sgapga = new swing.ButtonGradient();
        btn_session = new swing.ButtonGradient();
        btn_tablespace = new swing.ButtonGradient();
        btn_quanLyUser = new swing.ButtonGradient();
        btn_4 = new swing.ButtonGradient();
        btn_5 = new swing.ButtonGradient();
        btn_audit = new swing.ButtonGradient();
        btn_profile = new swing.ButtonGradient();
        btn_6 = new swing.ButtonGradient();
        btn_session1 = new swing.ButtonGradient();
        btn_session2 = new swing.ButtonGradient();
        btn_7 = new swing.ButtonGradient();
        btn_quaLaiMain = new swing.ButtonGradient();
        title1 = new swing.PanelRound();
        txt_search = new textfield.TextField();
        btn_search = new javax.swing.JLabel();
        btn_search4 = new javax.swing.JLabel();
        title3 = new swing.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_info = new javax.swing.JTable();
        lblHienthi6 = new javax.swing.JLabel();
        btn_load = new swing.ButtonGradient();
        title4 = new swing.PanelRound();
        txt_uname = new textfield.TextField();
        lblHienthi2 = new javax.swing.JLabel();
        lblHienthi3 = new javax.swing.JLabel();
        txt_uemail = new textfield.TextField();
        lblHienthi4 = new javax.swing.JLabel();
        txt_uimage = new textfield.TextField();
        btn_lamMoi = new swing.ButtonGradient();
        btn_xoa = new swing.ButtonGradient();
        btn_sua = new swing.ButtonGradient();
        btn_them = new swing.ButtonGradient();
        btn_jfileChooser = new swing.ButtonGradient();
        lbl_anh = new javax.swing.JLabel();
        lblHienthi7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tạo User tự động");

        panelRound2.setColorEnd(new java.awt.Color(0, 0, 0));
        panelRound2.setColorStart(new java.awt.Color(51, 51, 51));
        panelRound2.setPreferredSize(new java.awt.Dimension(1200, 690));

        title.setColorEnd(new java.awt.Color(102, 102, 102));
        title.setColorStart(new java.awt.Color(102, 102, 102));
        title.setRoundBottomLeft(15);
        title.setRoundBottomRight(15);
        title.setRoundTopLeft(15);
        title.setRoundTopRight(15);

        title2.setColorEnd(new java.awt.Color(0, 0, 0));
        title2.setColorStart(new java.awt.Color(51, 51, 51));
        title2.setRoundBottomLeft(15);
        title2.setRoundBottomRight(15);
        title2.setRoundTopLeft(15);
        title2.setRoundTopRight(15);

        lblHienthi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi1.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUser.png"))); // NOI18N
        lblHienthi1.setFocusable(false);
        lblHienthi1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi1.setIconTextGap(10);

        lblHienthi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi.setText("User name");
        lblHienthi.setFocusable(false);
        lblHienthi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi.setIconTextGap(10);

        javax.swing.GroupLayout title2Layout = new javax.swing.GroupLayout(title2);
        title2.setLayout(title2Layout);
        title2Layout.setHorizontalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title2Layout.createSequentialGroup()
                        .addComponent(lblHienthi1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title2Layout.createSequentialGroup()
                        .addComponent(lblHienthi)
                        .addGap(64, 64, 64))))
        );
        title2Layout.setVerticalGroup(
            title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHienthi1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHienthi)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        btn_sgapga.setText("Xem audit trigger");
        btn_sgapga.setColor1(new java.awt.Color(255, 0, 51));
        btn_sgapga.setColor2(new java.awt.Color(255, 0, 204));
        btn_sgapga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sgapga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sgapga.setIconTextGap(10);
        btn_sgapga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sgapgaActionPerformed(evt);
            }
        });

        btn_session.setText("Thông số session");
        btn_session.setColor1(new java.awt.Color(153, 0, 255));
        btn_session.setColor2(new java.awt.Color(0, 255, 204));
        btn_session.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_session.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_session.setIconTextGap(10);
        btn_session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sessionActionPerformed(evt);
            }
        });

        btn_tablespace.setText("Thông số tablespace");
        btn_tablespace.setColor1(new java.awt.Color(0, 0, 255));
        btn_tablespace.setColor2(new java.awt.Color(0, 255, 204));
        btn_tablespace.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tablespace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tablespace.setIconTextGap(10);
        btn_tablespace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tablespaceActionPerformed(evt);
            }
        });

        btn_quanLyUser.setText("Xem All User");
        btn_quanLyUser.setColor1(new java.awt.Color(255, 0, 255));
        btn_quanLyUser.setColor2(new java.awt.Color(255, 0, 153));
        btn_quanLyUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quanLyUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quanLyUser.setIconTextGap(10);
        btn_quanLyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quanLyUserActionPerformed(evt);
            }
        });

        btn_4.setText("Policy");
        btn_4.setColor1(new java.awt.Color(0, 0, 255));
        btn_4.setColor2(new java.awt.Color(0, 255, 204));
        btn_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.setIconTextGap(10);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setText("Quản lý quyền User");
        btn_5.setColor1(new java.awt.Color(255, 0, 204));
        btn_5.setColor2(new java.awt.Color(0, 255, 204));
        btn_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.setIconTextGap(10);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_audit.setText("Cảnh báo Audit");
        btn_audit.setColor1(new java.awt.Color(255, 0, 153));
        btn_audit.setColor2(new java.awt.Color(255, 102, 255));
        btn_audit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_audit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_audit.setIconTextGap(10);
        btn_audit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_auditActionPerformed(evt);
            }
        });

        btn_profile.setText("Quản lý profile");
        btn_profile.setColor1(new java.awt.Color(0, 0, 255));
        btn_profile.setColor2(new java.awt.Color(0, 255, 204));
        btn_profile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_profile.setIconTextGap(10);
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        btn_6.setText("Quản lý nhóm quyền");
        btn_6.setColor1(new java.awt.Color(255, 0, 204));
        btn_6.setColor2(new java.awt.Color(0, 255, 204));
        btn_6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.setIconTextGap(10);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_session1.setText("Session đang hoạt động");
        btn_session1.setColor1(new java.awt.Color(153, 0, 255));
        btn_session1.setColor2(new java.awt.Color(0, 255, 204));
        btn_session1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_session1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_session1.setIconTextGap(10);
        btn_session1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_session1ActionPerformed(evt);
            }
        });

        btn_session2.setText("Thông tin process");
        btn_session2.setColor1(new java.awt.Color(153, 0, 255));
        btn_session2.setColor2(new java.awt.Color(0, 255, 204));
        btn_session2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_session2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_session2.setIconTextGap(10);
        btn_session2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_session2ActionPerformed(evt);
            }
        });

        btn_7.setText("Audit");
        btn_7.setColor1(new java.awt.Color(255, 0, 204));
        btn_7.setColor2(new java.awt.Color(0, 255, 204));
        btn_7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.setIconTextGap(10);
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_quaLaiMain.setText("Quay lại form main");
        btn_quaLaiMain.setColor1(new java.awt.Color(255, 0, 102));
        btn_quaLaiMain.setColor2(new java.awt.Color(255, 153, 102));
        btn_quaLaiMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quaLaiMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quaLaiMain.setIconTextGap(10);
        btn_quaLaiMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaLaiMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(titleLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_audit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_quanLyUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tablespace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sgapga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_session1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_session2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_quaLaiMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_sgapga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_session, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_session1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_session2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quanLyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_audit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_quaLaiMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        title1.setColorEnd(new java.awt.Color(102, 102, 102));
        title1.setColorStart(new java.awt.Color(102, 102, 102));
        title1.setPreferredSize(new java.awt.Dimension(900, 50));
        title1.setRoundBottomLeft(15);
        title1.setRoundBottomRight(15);
        title1.setRoundTopLeft(15);
        title1.setRoundTopRight(15);

        txt_search.setForeground(new java.awt.Color(0, 204, 204));
        txt_search.setCaretColor(new java.awt.Color(0, 153, 153));
        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_search.setMargin(new java.awt.Insets(2, 15, 2, 15));
        txt_search.setRound(35);
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(102, 102, 102));
        btn_search.setOpaque(true);
        btn_search.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_searchMouseMoved(evt);
            }
        });
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });

        btn_search4.setBackground(new java.awt.Color(102, 102, 102));
        btn_search4.setIcon(new javax.swing.ImageIcon("C:\\Users\\caoho\\Downloads\\searchic1.png")); // NOI18N
        btn_search4.setOpaque(true);
        btn_search4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_search4MouseMoved(evt);
            }
        });
        btn_search4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout title1Layout = new javax.swing.GroupLayout(title1);
        title1.setLayout(title1Layout);
        title1Layout.setHorizontalGroup(
            title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search4)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        title1Layout.setVerticalGroup(
            title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(title1Layout.createSequentialGroup()
                        .addGroup(title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_search4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        title3.setColorEnd(new java.awt.Color(102, 102, 102));
        title3.setColorStart(new java.awt.Color(102, 102, 102));
        title3.setPreferredSize(new java.awt.Dimension(900, 607));
        title3.setRoundBottomLeft(15);
        title3.setRoundBottomRight(15);
        title3.setRoundTopLeft(15);
        title3.setRoundTopRight(15);

        tbl_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_infoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_info);

        lblHienthi6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi6.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi6.setText("Table User Infomation");
        lblHienthi6.setFocusable(false);
        lblHienthi6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi6.setIconTextGap(10);

        btn_load.setText("Load");
        btn_load.setColor1(new java.awt.Color(51, 255, 0));
        btn_load.setColor2(new java.awt.Color(0, 255, 255));
        btn_load.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_load.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_load.setIconTextGap(10);
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout title3Layout = new javax.swing.GroupLayout(title3);
        title3.setLayout(title3Layout);
        title3Layout.setHorizontalGroup(
            title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(title3Layout.createSequentialGroup()
                        .addComponent(lblHienthi6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        title3Layout.setVerticalGroup(
            title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHienthi6)
                    .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        title4.setBackground(new java.awt.Color(255, 255, 255));
        title4.setColorEnd(new java.awt.Color(102, 102, 102));
        title4.setColorStart(new java.awt.Color(102, 102, 102));
        title4.setPreferredSize(new java.awt.Dimension(900, 607));
        title4.setRoundBottomLeft(15);
        title4.setRoundBottomRight(15);
        title4.setRoundTopLeft(15);
        title4.setRoundTopRight(15);

        txt_uname.setForeground(new java.awt.Color(0, 204, 204));
        txt_uname.setCaretColor(new java.awt.Color(0, 204, 204));
        txt_uname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_uname.setRound(30);

        lblHienthi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi2.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi2.setText("User name");
        lblHienthi2.setFocusable(false);
        lblHienthi2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi2.setIconTextGap(10);

        lblHienthi3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi3.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi3.setText("Phone");
        lblHienthi3.setFocusable(false);
        lblHienthi3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi3.setIconTextGap(10);

        txt_uemail.setForeground(new java.awt.Color(0, 204, 204));
        txt_uemail.setCaretColor(new java.awt.Color(0, 204, 204));
        txt_uemail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_uemail.setRound(30);

        lblHienthi4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi4.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi4.setText("Image");
        lblHienthi4.setFocusable(false);
        lblHienthi4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi4.setIconTextGap(10);

        txt_uimage.setEditable(false);
        txt_uimage.setForeground(new java.awt.Color(0, 204, 204));
        txt_uimage.setCaretColor(new java.awt.Color(0, 204, 204));
        txt_uimage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_uimage.setRound(30);

        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.setColor1(new java.awt.Color(255, 0, 153));
        btn_lamMoi.setColor2(new java.awt.Color(255, 102, 255));
        btn_lamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_lamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_lamMoi.setIconTextGap(10);
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.setColor1(new java.awt.Color(255, 0, 0));
        btn_xoa.setColor2(new java.awt.Color(255, 0, 204));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_xoa.setIconTextGap(10);
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.setColor1(new java.awt.Color(102, 255, 0));
        btn_sua.setColor2(new java.awt.Color(255, 255, 0));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sua.setIconTextGap(10);
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_them.setText("Thêm");
        btn_them.setColor1(new java.awt.Color(255, 204, 0));
        btn_them.setColor2(new java.awt.Color(0, 255, 255));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_them.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_them.setIconTextGap(10);
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_jfileChooser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open_file_folder.png"))); // NOI18N
        btn_jfileChooser.setColor1(new java.awt.Color(254, 247, 247));
        btn_jfileChooser.setColor2(new java.awt.Color(204, 204, 0));
        btn_jfileChooser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_jfileChooser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_jfileChooser.setIconTextGap(10);
        btn_jfileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jfileChooserActionPerformed(evt);
            }
        });

        lbl_anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUser.png"))); // NOI18N
        lbl_anh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblHienthi7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi7.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi7.setText(" Path image");
        lblHienthi7.setFocusable(false);
        lblHienthi7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi7.setIconTextGap(10);

        javax.swing.GroupLayout title4Layout = new javax.swing.GroupLayout(title4);
        title4.setLayout(title4Layout);
        title4Layout.setHorizontalGroup(
            title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title4Layout.createSequentialGroup()
                .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(title4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_uimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(title4Layout.createSequentialGroup()
                        .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(title4Layout.createSequentialGroup()
                                .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, title4Layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(btn_jfileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, title4Layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(lblHienthi4)))
                                    .addGroup(title4Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblHienthi7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(title4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblHienthi2))
                            .addGroup(title4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(title4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(title4Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(lblHienthi3))
                                    .addComponent(txt_uemail, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(title4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        title4Layout.setVerticalGroup(
            title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblHienthi2)
                .addGap(7, 7, 7)
                .addComponent(txt_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHienthi3)
                .addGap(7, 7, 7)
                .addComponent(txt_uemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(title4Layout.createSequentialGroup()
                        .addComponent(lblHienthi4)
                        .addGap(7, 7, 7)
                        .addComponent(btn_jfileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHienthi7)
                .addGap(2, 2, 2)
                .addComponent(txt_uimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(title4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sessionActionPerformed
//        SessionMethod();
    }//GEN-LAST:event_btn_sessionActionPerformed

    private void btn_tablespaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tablespaceActionPerformed
        DataspaceForm data = new DataspaceForm();
        data.setVisible(true);
        data.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_tablespaceActionPerformed

    private void btn_quanLyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quanLyUserActionPerformed
        UserInformation userframe = new UserInformation();
        userframe.setVisible(true);
        userframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_quanLyUserActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        PolicyForm policyframe = new PolicyForm();
        policyframe.setVisible(true);
        policyframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        GrantUserForm grantuserform = new GrantUserForm();
        grantuserform.setVisible(true);
        grantuserform.setLocationRelativeTo(null);

    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_auditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_auditActionPerformed
        NotificationAudit f = new NotificationAudit(userNameIO ,passWordIO);
        f.setVisible(true);
        f.setLocationRelativeTo(null);

        //        AuditForm auditframe=new AuditForm();
        //        auditframe.setVisible(true);
        //        auditframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_auditActionPerformed

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        CreateProfileUser u = new CreateProfileUser();
        u.setVisible(true);
        u.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        NhomQuyenForm nhomquyenform = new NhomQuyenForm();
        nhomquyenform.setVisible(true);
        nhomquyenform.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_session1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_session1ActionPerformed
        KillsessionForm killform = new KillsessionForm();
        killform.setVisible(true);
        killform.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_session1ActionPerformed

    private void btn_session2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_session2ActionPerformed
//        initProcess();
    }//GEN-LAST:event_btn_session2ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        AuditForm auditframe = new AuditForm();
        auditframe.setVisible(true);
        auditframe.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_7ActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_searchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseMoved
        // TODO add your handling code here:
        btn_search.setBackground(new Color(239, 239, 239));
    }//GEN-LAST:event_btn_searchMouseMoved

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        // TODO add your handling code here:
        btn_search.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_search4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search4MouseMoved
        // TODO add your handling code here:
        btn_search.setBackground(new Color(239, 239, 239));
    }//GEN-LAST:event_btn_search4MouseMoved

    private void btn_search4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search4MouseClicked

    }//GEN-LAST:event_btn_search4MouseClicked

    private void btn_search4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search4MouseExited
        // TODO add your handling code here:
        btn_search.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btn_search4MouseExited

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        lamMoi();
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    public void lamMoi()
    {
        txt_uname.setText("");
        txt_uemail.setText("");
        txt_uimage.setText("");
        txt_uname.requestFocus();
        viTri = -1;
    }
    
    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            if(viTri < 0)
            {
                JOptionPane.showConfirmDialog(null, "Vui lòng chọn dòng để xóa", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                String name = txt_uname.getText();
                lUser.remove(viTri);
                String sql = "{call deleteUserInfo('"+name+"')}";
                CallableStatement cas = connect.prepareCall(sql);
                cas.executeQuery();
                
                JOptionPane.showConfirmDialog(null, "Xóa thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
                lamMoi();
                loadUser();
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Bạn không có quyền thao tác này!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ManagerIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try {
            if(viTri < 0)
            {
                JOptionPane.showConfirmDialog(null, "Vui lòng chọn dòng để cập nhật", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                String name = txt_uname.getText();
                String phone = txt_uemail.getText();
                String urlImage = txt_uimage.getText().toString();
                User user = lUser.get(viTri);
                int id = Integer.parseInt(user.getU_id());
                String sql = "{call updateUserInfo("+id+", '"+name+"','"+phone+"','"+urlImage+"')}";
                capNhatListUser(name, phone, urlImage);
                CallableStatement cas = connect.prepareCall(sql);
                cas.executeQuery();
                JOptionPane.showConfirmDialog(null, "Cập nhật thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
                lamMoi();
                loadUser();
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Bạn không có quyền thao tác này", "Thông báo", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ManagerIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    public void capNhatListUser(String name, String phone, String image)
    {
        User user = lUser.get(viTri);
        user.setU_name(name);
        user.setU_phone(phone);
        user.setU_image(image);
    }
    
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        String name = txt_uname.getText();
        String phone = txt_uemail.getText();
        String urlImage = txt_uimage.getText().toString();
        
        if(isNull() == false)
        {
            JOptionPane.showConfirmDialog(null, "Vui lòng nhập đầy đủ các trường", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(isNumber(txt_uemail.getText()) == false)
            {
                JOptionPane.showConfirmDialog(null, "Số điện thoại phải là số", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                String sql = "{call adduserinfor('"+name+"','"+phone+"','"+urlImage+"')}";//
                String sqlAutoUser = "{call taoTaik('"+name+"','"+phone+"')}";
                try {
                    CallableStatement cas = connect.prepareCall(sql);
                    cas.executeQuery();
                    
                    CallableStatement cas2 = connect.prepareCall(sqlAutoUser);
                    cas2.executeQuery();
                    JOptionPane.showConfirmDialog(null, "Thêm thành công", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    lamMoi();
                    loadUser();
                } catch (SQLException ex) {
                    Logger.getLogger(ManagerIO.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showConfirmDialog(null, "Bạn Không có quyền hạn này", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_jfileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jfileChooserActionPerformed
        JFileChooser jfileChooser = new JFileChooser();
        jfileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = jfileChooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File file = jfileChooser.getSelectedFile();
            filePath = file.getAbsolutePath().toString();
            txt_uimage.setText(filePath);
            
//            Hiển thị ảnh lên label
            ImageIcon image = new ImageIcon(new ImageIcon(filePath).getImage().getScaledInstance(lbl_anh.getWidth(), lbl_anh.getHeight(), Image.SCALE_SMOOTH));
            lbl_anh.setIcon(image);
        }
    }//GEN-LAST:event_btn_jfileChooserActionPerformed

    private void tbl_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_infoMouseClicked
        viTri = tbl_info.getSelectedRow();
        User user = lUser.get(viTri);
        txt_uname.setText(user.getU_name());
        txt_uemail.setText(user.getU_phone());
        txt_uimage.setText(user.getU_image());
        if(user.getU_image().trim().length() > 0)
        {
            ImageIcon icon = new ImageIcon(new ImageIcon(user.getU_image()).getImage().getScaledInstance(lbl_anh.getWidth(), lbl_anh.getHeight(), Image.SCALE_SMOOTH));
            lbl_anh.setIcon(icon);
        }
        txt_uname.requestFocus();
    }//GEN-LAST:event_tbl_infoMouseClicked

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        loadUser();
    }//GEN-LAST:event_btn_loadActionPerformed

    private void btn_quaLaiMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaLaiMainActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quaLaiMainActionPerformed

    private void btn_sgapgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sgapgaActionPerformed
        AuditUseTrigger information=new AuditUseTrigger(userNameIO, passWordIO);
        information.setVisible(true);
        information.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_sgapgaActionPerformed

    public boolean isEmail(String email)
    {
        String regex = "\\w+@\\w+\\.\\w+";
        if(email.matches(regex) == false)
        {
            return false;
        }
        return true;
    }
    
    public boolean isNumber(String number)
    {
        try{
            
            int so = Integer.parseInt(number);
            if(so < 0)
            {
                return false;
            }
        }
        catch(Exception e)
        {
            return false;
        }
        return true;
    }
    
    public boolean isNull() {
        String name = txt_uname.getText();
        String email = txt_uemail.getText();
        String urlImage = txt_uimage.getText();
        if (name.trim().length() == 0 || email.trim().length() == 0 || urlImage.trim().length() == 0) {
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new ManagerIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_4;
    private swing.ButtonGradient btn_5;
    private swing.ButtonGradient btn_6;
    private swing.ButtonGradient btn_7;
    private swing.ButtonGradient btn_audit;
    private swing.ButtonGradient btn_jfileChooser;
    private swing.ButtonGradient btn_lamMoi;
    private swing.ButtonGradient btn_load;
    private swing.ButtonGradient btn_profile;
    private swing.ButtonGradient btn_quaLaiMain;
    private swing.ButtonGradient btn_quanLyUser;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel btn_search4;
    private swing.ButtonGradient btn_session;
    private swing.ButtonGradient btn_session1;
    private swing.ButtonGradient btn_session2;
    private swing.ButtonGradient btn_sgapga;
    private swing.ButtonGradient btn_sua;
    private swing.ButtonGradient btn_tablespace;
    private swing.ButtonGradient btn_them;
    private swing.ButtonGradient btn_xoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHienthi;
    private javax.swing.JLabel lblHienthi1;
    private javax.swing.JLabel lblHienthi2;
    private javax.swing.JLabel lblHienthi3;
    private javax.swing.JLabel lblHienthi4;
    private javax.swing.JLabel lblHienthi6;
    private javax.swing.JLabel lblHienthi7;
    private javax.swing.JLabel lbl_anh;
    private swing.PanelRound panelRound2;
    private javax.swing.JTable tbl_info;
    private swing.PanelRound title;
    private swing.PanelRound title1;
    private swing.PanelRound title2;
    private swing.PanelRound title3;
    private swing.PanelRound title4;
    private textfield.TextField txt_search;
    private textfield.TextField txt_uemail;
    private textfield.TextField txt_uimage;
    private textfield.TextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
