/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlfile.FORM;

import Class.MahaFunction;
import Class.SYSConnection;
import Class.UserInSys;
import java.sql.Statement;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;
/**
 *
 * @author Kiêt
 */
public class UserInformation extends javax.swing.JFrame {
    public SYSConnection sysCon;
    public Connection con;
    DefaultTableModel model;
    List<UserInSys> lUserSys;
    
    public UserInformation() {
        sysCon = new SYSConnection();
        con = sysCon.getConnection();
        initComponents();
        lUserSys = new ArrayList<>();
        model = (DefaultTableModel) tb_hienThiUser.getModel();
        this.setLocationRelativeTo(null);
        try {
            loadCBB();
            loadtb();
        } catch (SQLException ex) {
            Logger.getLogger(UserInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound3 = new swing.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_hienThiUser = new javax.swing.JTable();
        cbb_users = new javax.swing.JComboBox<>();
        lblHienthi6 = new javax.swing.JLabel();
        lblHienthi7 = new javax.swing.JLabel();
        panelRound2 = new swing.PanelRound();
        btn_htUser = new swing.ButtonGradient();
        btn_xoaProfile = new swing.ButtonGradient();
        btn_quayLai1 = new swing.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xem thông tin liên quan đến một user ");

        panelRound3.setBackground(new java.awt.Color(0, 51, 51));
        panelRound3.setPreferredSize(new java.awt.Dimension(100, 720));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        tb_hienThiUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_hienThiUser);

        lblHienthi6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi6.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi6.setText("Bảng thông tin tất cả user trong hệ thống");
        lblHienthi6.setFocusable(false);
        lblHienthi6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi6.setIconTextGap(10);

        lblHienthi7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienthi7.setForeground(new java.awt.Color(255, 255, 255));
        lblHienthi7.setText("Chọn người dùng để hiển thị");
        lblHienthi7.setFocusable(false);
        lblHienthi7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHienthi7.setIconTextGap(10);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHienthi7)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addComponent(cbb_users, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(lblHienthi6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblHienthi6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHienthi7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addComponent(cbb_users, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelRound2.setBackground(new java.awt.Color(0, 51, 51));
        panelRound2.setPreferredSize(new java.awt.Dimension(100, 720));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        btn_htUser.setText("Hiển thị thông tin");
        btn_htUser.setColor1(new java.awt.Color(51, 255, 255));
        btn_htUser.setColor2(new java.awt.Color(255, 0, 255));
        btn_htUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_htUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_htUserActionPerformed(evt);
            }
        });

        btn_xoaProfile.setText("Thông tin tuyệt đối");
        btn_xoaProfile.setColor1(new java.awt.Color(255, 255, 51));
        btn_xoaProfile.setColor2(new java.awt.Color(255, 102, 0));
        btn_xoaProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaProfileActionPerformed(evt);
            }
        });

        btn_quayLai1.setText("Quay lại");
        btn_quayLai1.setColor1(new java.awt.Color(255, 0, 255));
        btn_quayLai1.setColor2(new java.awt.Color(255, 102, 0));
        btn_quayLai1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_quayLai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quayLai1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_htUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_xoaProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_quayLai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btn_htUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_xoaProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_quayLai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadCBB() throws SQLException
    {
        String sql = "{call getAlluser(?)}";
        CallableStatement cas = con.prepareCall(sql);
        cas.registerOutParameter(1, OracleTypes.CURSOR);
        cas.executeQuery();
        ResultSet rs = (ResultSet) cas.getObject(1);
        while(rs.next())
        {
            cbb_users.addItem(rs.getString("USERNAME"));
        }
    }
    
    public void loadtb() throws SQLException
    {
        String sql = "{call getAlluser(?)}";
        CallableStatement cas = con.prepareCall(sql);
        cas.registerOutParameter(1, OracleTypes.CURSOR);
        cas.executeQuery();
        ResultSet rs = (ResultSet) cas.getObject(1);
        model.setRowCount(0);
        lUserSys.clear();
        model.setColumnIdentifiers(new Object[]{"USERNAME", "CREATED", "EXPIRY_DATE",
            "ACCOUNT_STATUS", "LAST_LOGIN", "PROFILE"});
        try {
            while(rs.next())
            {
                lUserSys.add(new UserInSys(rs.getString("USERNAME"),
                rs.getString("CREATED"), rs.getString("EXPIRY_DATE"), rs.getString("ACCOUNT_STATUS"),
                        rs.getString("LAST_LOGIN"), rs.getString("PROFILE")));
                Object obj[] = {rs.getString("USERNAME"), rs.getString("CREATED"),
                    rs.getString("EXPIRY_DATE"), rs.getString("ACCOUNT_STATUS"),
                    rs.getString("LAST_LOGIN"), rs.getString("PROFILE")};
                model.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void btn_htUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_htUserActionPerformed
        String userName = (String) cbb_users.getSelectedItem();
        model.setRowCount(0);
        for (UserInSys us : lUserSys) {
            if (us.getUSERNAME().contains(userName)) {
                Object obj[] = {us.getUSERNAME(), us.getCREATED(), us.getEXPIRY_DATE(),
                    us.getACCOUNT_STATUS(), us.getLAST_LOGIN(), us.getPROFILE()};
                model.addRow(obj);
            }
        }
    }//GEN-LAST:event_btn_htUserActionPerformed

    private void btn_xoaProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaProfileActionPerformed
        String userName = (String) cbb_users.getSelectedItem();
        model.setRowCount(0);
        for (UserInSys us : lUserSys) {
            if (us.getUSERNAME().equalsIgnoreCase(userName)) {
                Object obj[] = {us.getUSERNAME(), us.getCREATED(), us.getEXPIRY_DATE(),
                    us.getACCOUNT_STATUS(), us.getLAST_LOGIN(), us.getPROFILE()};
                model.addRow(obj);
            }
        }
    }//GEN-LAST:event_btn_xoaProfileActionPerformed

    private void btn_quayLai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quayLai1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_quayLai1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_htUser;
    private swing.ButtonGradient btn_quayLai1;
    private swing.ButtonGradient btn_xoaProfile;
    private javax.swing.JComboBox<String> cbb_users;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHienthi6;
    private javax.swing.JLabel lblHienthi7;
    private swing.PanelRound panelRound2;
    private swing.PanelRound panelRound3;
    private javax.swing.JTable tb_hienThiUser;
    // End of variables declaration//GEN-END:variables
}
